// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TheOmenDen.CrowsAgainstHumility.Importer.contexts;
using TheOmenDen.CrowsAgainstHumility.Importer.Models;

#nullable disable

namespace TheOmenDen.CrowsAgainstHumility.Importer.contexts.Configurations
{
    public partial class PackConfiguration : IEntityTypeConfiguration<Pack>
    {
        public void Configure(EntityTypeBuilder<Pack> entity)
        {
            entity.HasIndex(e => e.IsOfficialPack, "IX_Packs_IsOfficialPack");

            entity.HasIndex(e => e.Name, "IX_Packs_Name");

            entity.Property(e => e.Id).HasDefaultValueSql("(newsequentialid())");

            entity.Property(e => e.Description).HasMaxLength(1000);

            entity.Property(e => e.Name).HasMaxLength(200);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Pack> entity);
    }
}
