// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TheOmenDen.CrowsAgainstHumility.Importer.Models
{
    public partial class Pack
    {
        public Pack()
        {
            BlackCards = new HashSet<BlackCard>();
            WhiteCards = new HashSet<WhiteCard>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; } = null!;
        public string Description { get; set; } = null!;
        public bool IsOfficialPack { get; set; }

        public virtual ICollection<BlackCard> BlackCards { get; set; }
        public virtual ICollection<WhiteCard> WhiteCards { get; set; }
    }
}